### ISSUE TITLE
ImportError: No module named siever_params

### ISSUE THREAD

**Issue by yujie6** [WvanWoerden/G6K-GPU-Tensor#1]
I installed all the dependents, and got my GPU(GTX1660S) as well...
But there is an error when running the first challenge `./svp_challenge.py 100 --threads 4 --gpus 1 --verbose`
```
Traceback (most recent call last):
  File "./svp_challenge.py", line 14, in <module>
    from g6k.algorithms.workout import workout
  File "/home/lattice/Documents/G6K-GPU-Tensor/g6k/__init__.py", line 3, in <module>
    from .siever_params import SieverParams # noqa
ImportError: No module named siever_params
```
By the way, did you considered updating to python3 since py2 was already deprecated

**Comment by WvanWoerden** [comment]
Did you successfully run the following commands first without errors?
```
source g6k-env/bin/activate
./rebuild.sh -f -y
```
I personally have no plan currently to invest the time to update to Python 3. It could potentially be done by carefully reapplying the Python 3 support pull request of https://github.com/fplll/g6k/pull/17 .

**Comment by yujie6** [comment]
Well, I got 27 errors, all of them are like the following:
```
./cuda/GPUStreamGeneral.cu(769): error: identifier "__habs2" is undefined
```
It seems that there's something wrong with cuda, does that mean I haven't installed some cuda libs? I have nvcc and nvidia-smi worked fine though.

**Comment by WvanWoerden** [comment]
Those functions are pretty new and you need at least cuda 10.2 for them to work.
I just noticed you mentioned a GTX card. Unfortunately this code needs Tensor cores to function and thus requires an RTX card. Also the code has only been tested on RTX 2080 Ti and Titan RTX cards.

**Comment by yujie6** [comment]
Thanks a lot! I will try it on RTX later.
