### ISSUE TITLE
Error when installing G6K-GPU-Tensor after installing both fplll and fpylll successfully

### ISSUE THREAD

**Issue by thomas-li-sjtu** [WvanWoerden/G6K-GPU-Tensor#14]
The following messages are printed:

../cuda/GPUStreamGeneral.cu(769): error: identifier "__habs2" is undefined
          detected during:
            instantiation of "void kernel_bdgl_subbucketing<VECDIM,v_packs,MH>(half2 *, curandState, uint32_t, uint32_t, int *, half *) [with VECDIM=96, v_packs=4, MH=4]" 
(1003): here
            instantiation of "void kernel_bdgl_bucketing_2block<VECDIM,MH>(const half *, int32_t, uint32_t, int, uint32_t, indextype *, half *) [with VECDIM=160, MH=4]" 
(2538): here

../cuda/GPUStreamGeneral.cu(769): error: identifier "__habs2" is undefined
          detected during:
            instantiation of "void kernel_bdgl_subbucketing<VECDIM,v_packs,MH>(half2 *, curandState, uint32_t, uint32_t, int *, half *) [with VECDIM=64, v_packs=4, MH=8]" 
(1003): here
            instantiation of "void kernel_bdgl_bucketing_2block<VECDIM,MH>(const half *, int32_t, uint32_t, int, uint32_t, indextype *, half *) [with VECDIM=96, MH=8]" 
(2542): here

../cuda/GPUStreamGeneral.cu(769): error: identifier "__habs2" is undefined
          detected during:
            instantiation of "void kernel_bdgl_subbucketing<VECDIM,v_packs,MH>(half2 *, curandState, uint32_t, uint32_t, int *, half *) [with VECDIM=96, v_packs=4, MH=8]" 
(1003): here
            instantiation of "void kernel_bdgl_bucketing_2block<VECDIM,MH>(const half *, int32_t, uint32_t, int, uint32_t, indextype *, half *) [with VECDIM=160, MH=8]" 
(2544): here

../cuda/GPUStreamGeneral.cu(769): error: identifier "__habs2" is undefined
          detected during:
            instantiation of "void kernel_bdgl_subbucketing<VECDIM,v_packs,MH>(half2 *, curandState, uint32_t, uint32_t, int *, half *) [with VECDIM=64, v_packs=4, MH=16]" 
(1003): here
            instantiation of "void kernel_bdgl_bucketing_2block<VECDIM,MH>(const half *, int32_t, uint32_t, int, uint32_t, indextype *, half *) [with VECDIM=96, MH=16]" 
(2548): here

../cuda/GPUStreamGeneral.cu(769): error: identifier "__habs2" is undefined
          detected during:
            instantiation of "void kernel_bdgl_subbucketing<VECDIM,v_packs,MH>(half2 *, curandState, uint32_t, uint32_t, int *, half *) [with VECDIM=96, v_packs=4, MH=16]" 
(1003): here
            instantiation of "void kernel_bdgl_bucketing_2block<VECDIM,MH>(const half *, int32_t, uint32_t, int, uint32_t, indextype *, half *) [with VECDIM=160, MH=16]" 
(2550): here

../cuda/GPUStreamGeneral.cu(1446): error: expected a comma (the one-argument version of static_assert is not enabled in this mode)

../cuda/cuda_tensor_wmma.hpp(506): error: expected a comma (the one-argument version of static_assert is not enabled in this mode)
          detected during instantiation of "void kernel_triple_sieve<VECDIM,TRIPLE>(half *, const half *, const half *, uint32_t, uint32_t *, int *) [with VECDIM=32, TRIPLE=true]" 
../cuda/GPUStreamGeneral.cu(2707): here

../cuda/cuda_tensor_wmma.hpp(500): error: expected a comma (the one-argument version of static_assert is not enabled in this mode)
          detected during instantiation of "void kernel_triple_sieve<VECDIM,TRIPLE>(half *, const half *, const half *, uint32_t, uint32_t *, int *) [with VECDIM=32, TRIPLE=true]" 
../cuda/GPUStreamGeneral.cu(2707): here

../cuda/GPUStreamGeneral.cu(1703): warning: variable "BL" was declared but never referenced

48 errors detected in the compilation of "/tmp/tmpxft_00005790_00000000-6_GPUStreamGeneral.cpp1.ii".
Makefile:51: recipe for target '../cuda/GPUStreamGeneral.o' failed
make: *** [../cuda/GPUStreamGeneral.o] Error 1
make: Leaving directory '/backup1/G6K-GPU/G6K-GPU-Tensor/kernel'
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    subprocess.check_call("make -C kernel",shell=True)
  File "/backup1/G6K-GPU/conda/G6K/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'make -C kernel' returned non-zero exit status 2.

Is there something wrong with cuda/GPUStreamGeneral.cu?
Looking forward to your reply.

**Comment by thomas-li-sjtu** [comment]
By the way, could you tell me which version of gcc did you test in nvidia platform?

**Comment by thomas-li-sjtu** [comment]
Problem solved. It seems that I should update my gcc to 8.4. Note that gcc version 9.4 is not suitable either.

**Comment by Bruce-Luuuu** [comment]
> Problem solved. It seems that I should update my gcc to 8.4. Note that gcc version 9.4 is not suitable either.

Now my gcc version is 9.4.0, so I should reinstall the 8.4 version, right?
