### ISSUE TITLE
cysignals.signals.SignalError: Segmentation fault

### ISSUE THREAD

**Issue by yujie6** [WvanWoerden/G6K-GPU-Tensor#2]
I got my RTX3090, and installed the right cuda version. But still got some errors:
```
(g6k-env) root@f7ce6475b8cc:/app# ./svp_challenge.py 5 --threads 4 --gpus 1 --verbose
root: Did not find 'svpchallenge/svpchallenge-dim-005-seed-00.txt', downloading ...
root: 200 OK
Loaded challenge dim 5
gh = 449545.058830, goal_r0/gh = 1.102500, r0/gh = 0.112383
Traceback (most recent call last):
  File "./svp_challenge.py", line 142, in <module>
    asvp()
  File "./svp_challenge.py", line 116, in asvp
    seed=args.seed)
  File "/app/g6k/utils/cli.py", line 109, in run_all
    res = f(copy.deepcopy(job))
  File "./svp_challenge.py", line 77, in asvp_kernel
    pump_params=pump_params, **workout_params)
  File "/app/g6k/algorithms/workout.py", line 54, in workout
    flast = min( flast, pump(g6k, tracer, kappa, blocksize, f, goal_r0=goal_r0, **pump_params))
  File "/app/g6k/algorithms/pump.py", line 137, in pump
    wrapped_sieve(pump)  # The first initializing Sieve should always be Gauss to avoid rank-loss
  File "/app/g6k/algorithms/pump.py", line 33, in wrapped_sieve
    pump.g6k(alg=alg, tracer=pump.tracer)
  File "g6k/siever.pyx", line 1266, in g6k.siever.Siever.__call__
    with tracer.context("gauss"):
  File "g6k/siever.pyx", line 1267, in g6k.siever.Siever.__call__
    self.gauss_sieve(reset_stats=reset_stats)
  File "g6k/siever.pyx", line 1237, in g6k.siever.Siever.gauss_sieve
    sig_on()
cysignals.signals.SignalError: Segmentation fault
```
It seems that the gauss_sieve function built from cython caused it, any ideas?

**Comment by thomas-li-sjtu** [comment]
Hi, I wonder if you have solved the problem? I meet the same error. Could you tell me how to solve it?

My cuda version is 11.2, gcc version is 8.4 (the same as g++ version). The code I cloned is lwe_gpu_chal. Looking forward to your reply.

```
(g6k-env) (G6k-Gpu) project@fas:~/G6K-GPU-Tensor$ python svp_challenge.py 10 --threads 4 --gpus 1 --gpu_bucketer bdgl --verbose
Loaded challenge dim 10
gh = 829363.086780, goal_r0/gh = 1.102500, r0/gh = 0.867051
Traceback (most recent call last):
  File "svp_challenge.py", line 142, in <module>
    asvp()
  File "svp_challenge.py", line 116, in asvp
    seed=args.seed)
  File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/utils/cli.py", line 109, in run_all
    res = f(copy.deepcopy(job))
  File "svp_challenge.py", line 77, in asvp_kernel
    pump_params=pump_params, **workout_params)
  File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/algorithms/workout.py", line 54, in workout
    flast = min( flast, pump(g6k, tracer, kappa, blocksize, f, goal_r0=goal_r0, **pump_params))
  File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/algorithms/pump.py", line 140, in pump
    wrapped_sieve(pump)  # The first initializing Sieve should always be Gauss to avoid rank-loss
  File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/algorithms/pump.py", line 36, in wrapped_sieve
    pump.g6k(alg=alg, tracer=pump.tracer)
  File "g6k/siever.pyx", line 1264, in g6k.siever.Siever.__call__
    with tracer.context("gauss"):
  File "g6k/siever.pyx", line 1265, in g6k.siever.Siever.__call__
    self.gauss_sieve(reset_stats=reset_stats)
  File "g6k/siever.pyx", line 1235, in g6k.siever.Siever.gauss_sieve
    sig_on()
cysignals.signals.SignalError: Segmentation fault
```

**Comment by thomas-li-sjtu** [comment]
My cuda version is 11.2, gcc version is 8.4 (the same as g++ version). The code I cloned is lwe_gpu_chal. Looking forward to your reply.

**Comment by yujie6** [comment]
> Hi, I wonder if you have solved the problem? I meet the same error. Could you tell me how to solve it?
> 
> My cuda version is 11.2, gcc version is 8.4 (the same as g++ version). The code I cloned is lwe_gpu_chal. Looking forward to your reply.
> 
> ```
> (g6k-env) (G6k-Gpu) project@fas:~/G6K-GPU-Tensor$ python svp_challenge.py 10 --threads 4 --gpus 1 --gpu_bucketer bdgl --verbose
> Loaded challenge dim 10
> gh = 829363.086780, goal_r0/gh = 1.102500, r0/gh = 0.867051
> Traceback (most recent call last):
>   File "svp_challenge.py", line 142, in <module>
>     asvp()
>   File "svp_challenge.py", line 116, in asvp
>     seed=args.seed)
>   File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/utils/cli.py", line 109, in run_all
>     res = f(copy.deepcopy(job))
>   File "svp_challenge.py", line 77, in asvp_kernel
>     pump_params=pump_params, **workout_params)
>   File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/algorithms/workout.py", line 54, in workout
>     flast = min( flast, pump(g6k, tracer, kappa, blocksize, f, goal_r0=goal_r0, **pump_params))
>   File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/algorithms/pump.py", line 140, in pump
>     wrapped_sieve(pump)  # The first initializing Sieve should always be Gauss to avoid rank-loss
>   File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/algorithms/pump.py", line 36, in wrapped_sieve
>     pump.g6k(alg=alg, tracer=pump.tracer)
>   File "g6k/siever.pyx", line 1264, in g6k.siever.Siever.__call__
>     with tracer.context("gauss"):
>   File "g6k/siever.pyx", line 1265, in g6k.siever.Siever.__call__
>     self.gauss_sieve(reset_stats=reset_stats)
>   File "g6k/siever.pyx", line 1235, in g6k.siever.Siever.gauss_sieve
>     sig_on()
> cysignals.signals.SignalError: Segmentation fault
> ```

As far as I know, changing challenge dimension to 100 solved the problem.

**Comment by thomas-li-sjtu** [comment]
> > Hi, I wonder if you have solved the problem? I meet the same error. Could you tell me how to solve it?
> > My cuda version is 11.2, gcc version is 8.4 (the same as g++ version). The code I cloned is lwe_gpu_chal. Looking forward to your reply.
> > ```
> > (g6k-env) (G6k-Gpu) project@fas:~/G6K-GPU-Tensor$ python svp_challenge.py 10 --threads 4 --gpus 1 --gpu_bucketer bdgl --verbose
> > Loaded challenge dim 10
> > gh = 829363.086780, goal_r0/gh = 1.102500, r0/gh = 0.867051
> > Traceback (most recent call last):
> >   File "svp_challenge.py", line 142, in <module>
> >     asvp()
> >   File "svp_challenge.py", line 116, in asvp
> >     seed=args.seed)
> >   File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/utils/cli.py", line 109, in run_all
> >     res = f(copy.deepcopy(job))
> >   File "svp_challenge.py", line 77, in asvp_kernel
> >     pump_params=pump_params, **workout_params)
> >   File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/algorithms/workout.py", line 54, in workout
> >     flast = min( flast, pump(g6k, tracer, kappa, blocksize, f, goal_r0=goal_r0, **pump_params))
> >   File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/algorithms/pump.py", line 140, in pump
> >     wrapped_sieve(pump)  # The first initializing Sieve should always be Gauss to avoid rank-loss
> >   File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/algorithms/pump.py", line 36, in wrapped_sieve
> >     pump.g6k(alg=alg, tracer=pump.tracer)
> >   File "g6k/siever.pyx", line 1264, in g6k.siever.Siever.__call__
> >     with tracer.context("gauss"):
> >   File "g6k/siever.pyx", line 1265, in g6k.siever.Siever.__call__
> >     self.gauss_sieve(reset_stats=reset_stats)
> >   File "g6k/siever.pyx", line 1235, in g6k.siever.Siever.gauss_sieve
> >     sig_on()
> > cysignals.signals.SignalError: Segmentation fault
> > ```
> 
> As far as I know, changing challenge dimension to 100 solved the problem.

Thanks for your reply! I tried but another problem occurred. That's why I changed it to 10. Here is the output.

```
$ python svp_challenge.py 100 --threads 4 --gpus 1 | tee ../svp_challenge.logs
Loaded challenge dim 100
gh = 6449194.089993, goal_r0/gh = 1.102500, r0/gh = 7.053307
CUDA Error (../cuda/GPUStreamGeneral.cu@l2278): no kernel image is available for execution on the device
Traceback (most recent call last):
  File "svp_challenge.py", line 142, in <module>
    asvp()
  File "svp_challenge.py", line 116, in asvp
    seed=args.seed)
  File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/utils/cli.py", line 109, in run_all
    res = f(copy.deepcopy(job))
  File "svp_challenge.py", line 77, in asvp_kernel
    pump_params=pump_params, **workout_params)
  File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/algorithms/workout.py", line 54, in workout
    flast = min( flast, pump(g6k, tracer, kappa, blocksize, f, goal_r0=goal_r0, **pump_params))
  File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/algorithms/pump.py", line 140, in pump
    wrapped_sieve(pump)  # The first initializing Sieve should always be Gauss to avoid rank-loss
  File "/home/project/lhz/G6k/G6K-GPU-Tensor/g6k/algorithms/pump.py", line 36, in wrapped_sieve
    pump.g6k(alg=alg, tracer=pump.tracer)
  File "g6k/siever.pyx", line 1261, in g6k.siever.Siever.__call__
    with tracer.context("gpu"):
  File "g6k/siever.pyx", line 1262, in g6k.siever.Siever.__call__
    self.gpu_sieve(reset_stats=reset_stats) 
  File "g6k/siever.pyx", line 1170, in g6k.siever.Siever.gpu_sieve
    sig_on()
RuntimeError: Aborted
```

**Comment by WvanWoerden** [comment]
The GPU sieve uses much less information per vector than the CPU based sieves. Running `rebuild.sh` with the `-y` flag removes this extra information per vector, which means that the CPU sieves do not work anymore. The svp_challenge and the workout/pumps therein default to the use of a Gauss sieve in dimensions <40 (or 50), and that will crash. 

The other error is a generic CUDA error which I can't directly help you with. It might be related to your specific newer generation RTX3090 card. We have only ever tested the code on the Turing generation cards (RTX20xx). You might have to increase the compute capability in the Makefile: https://github.com/WvanWoerden/G6K-GPU-Tensor/blob/221336be89c227f25cc668c1c11172f442cc4146/kernel/Makefile#L18
